server:
  port: 8080
  servlet:
    context-path: /poc-mp

spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dwlocal

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

app:
  debugMode: true


appConfig:
  runConfig: false
  fetchSize: 1500
  pageSize: 1500
  numberOfLinesToReturnForHealthLog: 10
  useWhereClause: true
  reducerBeginDate: 20190301
  reducerEndDate: 20190731
  sampleDwEventFilePath: /resources/postpayload.json,
  KafkaServers: localhost:9092,localhost:9093,localhost:9094
  ZookeeperServers: localhost:2181

